name: Scrape 8-k Files Every-day

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git user identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          python -m pip install --upgrade pip
          pip install selenium pandas

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &

      - name: Run Python script
        env:
          DISPLAY: :99
        run: python app.py

      - name: Commit changes to overall.csv
        run: |
          git add data/overall.csv
          git commit -m "Update overall.csv"
          git push
