name: Scrape 8-k Files Every-day

on:
  workflow_dispatch
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          python -m pip install --upgrade pip
          pip install selenium pandas

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &

      - name: Run Python script
        env:
          DISPLAY: :99
        run: python app.py

      - name: Check if overall.csv has changes
        id: check_changes
        run: |
          git diff --quiet data/overall.csv || echo "changes"
        continue-on-error: true

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'changes'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/overall.csv
          git commit -m "Update overall.csv"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/ASP-Christian/8kfiles.git

      - name: Write to daily_report.txt if no data gathered
        if: steps.check_changes.outputs.changes != 'changes'
        run: |
          echo "$(date +"%Y-%m-%d") has no 8-K filings with Item 1.05 found." >> daily_report.txt
